openapi: 3.2.0
info:
  title: Servicing Disclosure Templates API
  description: Servicing supports a buyer's post purchase journey, enabling viewing and management of payment agreements across all payment products.
  version: 2.0.0
  contact:
    email: partnership-growth@getbread.com
servers:
- url: https://api-preview.platform.breadpayments.com/
  description: Preview environment
- url: https://api.platform.breadpayments.com/
  description: Production environment
tags:
- name: Disclosure Templates
paths:
  /api/disclosure/template/{disclosureName}/program/{programID}:
    get:
      summary: Get a disclosure template
      description: Get a disclosure template document by program ID and disclosure name
      operationId: getTemplate
      tags:
      - Disclosure Templates
      security:
      - bearerAuthDisclosure:
        - r:disclosure.template
      parameters:
      - in: header
        name: X-API-VERSION
        description: 'X-API-VERSION: Header to specify the API version (i.e. v2)'
        schema:
          type: string
        required: true
      - name: programID
        in: path
        required: true
        description: The UUID of the program the agreement product is associated with
        schema:
          type: string
          format: uuid
          description: A universally unique identifier (Version 4) as defined in RFC4122. This does not allow nulls.
          example: dc0dc633-1760-4d43-ba1d-da94ed701f06
          externalDocs:
            description: RFC4122
            url: https://datatracker.ietf.org/doc/html/rfc4122.html
      - name: disclosureName
        in: path
        description: The name of the required disclosure
        required: true
        schema:
          description: A symbol identifying a disclosure document type
          type: string
          enum:
          - loan-agreement
          - loan-agreement-sp
          - cob-activation
          - cob-maintenance
          - one-time
          - auto-enroll
          - auto-enroll-sp
          - auto-enroll-pending
          - scheduled-payment
          - tila
          - credit-score-notice
          - auto-enroll-past-due
          - auto-enroll-past-due-sp
          - payment-full-terms
          - copy-of-authorization
          - copy-of-authorization-sp
          - checkout-auto-enroll-sp
          - hardship-confirm-0
          - hardship-confirm-29
          - hardship-confirm-59
          - verification-service
          - poa
          - payment-confirm
          - statement-hyloc
          - loan-agreement-hyloc
          - tila-hyloc
          - auto-enroll-full-terms
          - statement-di
          - loan-agreement-di
          - tila-di
          - ''
          example: loan-agreement
      responses:
        '200':
          description: OK. The rendered disclosure markup.
          content:
            text/html:
              schema:
                type: string
                example: "<html lang=\"en\"> <head>\n <title>Truth In Lending Disclosure Statement</title>\n </head>\n <body>\n <div>\n <h1>TRUTH IN LENDING DISCLOSURE STATEMENT</h1>\n <div class=\"flex\">\n <div class=\"small-width\" data-testId=\"creditor\">\n <strong>Creditor:</strong><br />\n Comenity Capital Bank<br />\n PO Box 11499<br />\n Tampa, FL 33680<br />\n </div>\n </div>\n {{ end }}\n </div>\n </body></html>"
            text/plain:
              schema:
                type: string
                example: Truth In Lending Disclosure Statement
            application/pdf:
              schema:
                type: string
                format: binary
                description: The disclosure document rendered as a PDF file.
        '400':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                - type: object
                  description: Disclosure service error response
                  properties:
                    reason:
                      type: string
                      description: Disclosure error reason codes
                      enum:
                      - RESOURCE_NOT_FOUND
                      - RETRIEVAL_ERROR
                      - WRITE_ERROR
                      - SERVICE_ERROR
                      - VALIDATION_FAILURE
                      - INVARIANT_VIOLATED
                      - SYSTEM_ERROR
                      - POLICY_ERROR
                      - BAD_AUTHENTICATION
                      - NOT_AUTHORIZED
                      - INVALID
                      - UNKNOWN
                      example: RESOURCE_NOT_FOUND
                  required:
                  - code
                  - domain
                  - message
                  - reason
                example:
                  code: 404
                  domain: disclosures
                  message: retrieving disclosure record
                  reason: RESOURCE_NOT_FOUND
        '401':
          description: Unauthorized. Indicates that provided credentials is not valid
          content:
            text/plain:
              schema:
                type: string
                example: Jwt is expired
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 401
                domain: Auth
                message: Invalid authentication
                reason: Invalid_Authentication
        '403':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                - type: object
                  description: Disclosure service error response
                  properties:
                    reason:
                      type: string
                      description: Disclosure error reason codes
                      enum:
                      - RESOURCE_NOT_FOUND
                      - RETRIEVAL_ERROR
                      - WRITE_ERROR
                      - SERVICE_ERROR
                      - VALIDATION_FAILURE
                      - INVARIANT_VIOLATED
                      - SYSTEM_ERROR
                      - POLICY_ERROR
                      - BAD_AUTHENTICATION
                      - NOT_AUTHORIZED
                      - INVALID
                      - UNKNOWN
                      example: RESOURCE_NOT_FOUND
                  required:
                  - code
                  - domain
                  - message
                  - reason
                example:
                  code: 404
                  domain: disclosures
                  message: retrieving disclosure record
                  reason: RESOURCE_NOT_FOUND
        '500':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                - type: object
                  description: Disclosure service error response
                  properties:
                    reason:
                      type: string
                      description: Disclosure error reason codes
                      enum:
                      - RESOURCE_NOT_FOUND
                      - RETRIEVAL_ERROR
                      - WRITE_ERROR
                      - SERVICE_ERROR
                      - VALIDATION_FAILURE
                      - INVARIANT_VIOLATED
                      - SYSTEM_ERROR
                      - POLICY_ERROR
                      - BAD_AUTHENTICATION
                      - NOT_AUTHORIZED
                      - INVALID
                      - UNKNOWN
                      example: RESOURCE_NOT_FOUND
                  required:
                  - code
                  - domain
                  - message
                  - reason
                example:
                  code: 404
                  domain: disclosures
                  message: retrieving disclosure record
                  reason: RESOURCE_NOT_FOUND
components:
  securitySchemes:
    bearerAuthServicing:
      type: http
      scheme: bearer
      bearerFormat: JWT
    bearerAuthDisclosure:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token provided by the Auth service
