openapi: 3.2.0
info:
  title: webhook Events API
  description: Provides support for managing webhook subscriber's events by allowing them to query, and ultimately replay past failed events.
  version: 2.0.0
  contact:
    email: Core-Eng@breadfinancial.com
servers:
- url: https://api-preview.platform.breadpayments.com/
  description: Preview environment
- url: https://api.platform.breadpayments.com/
  description: Production environment
tags:
- name: Events
  description: Event status retrieval and replay mechanism
paths:
  /api/webhook/subscription/{name}/event:
    get:
      tags:
      - Events
      summary: List events
      description: Allows a user to retrieve all events for a subscription by supplying the subscription name and optionally one or more event statuses.
      operationId: getEventBySubscriptionAndStatus
      security:
      - bearerAuthWebhook:
        - r:webhook.event
      parameters:
      - name: name
        description: Name of the subscription
        in: path
        required: true
        schema:
          type: string
        example: Test1SubscriptionEndpoint-dbef2daf-f94a-41f3-8d07-52eb17cc17b3
      - name: status.eq
        description: Status of the event
        in: query
        schema:
          type: array
          items:
            type: string
            enum:
            - SUCCESS
            - FAILURE
            - PENDING
      - name: from
        description: Point in time to start lookup (optional). Required if TimeTo is provided.
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
          description: The timestamp value formatted per RFC3339. This does allow nulls.
          example: '2020-12-31T15:10:55Z'
          externalDocs:
            description: RFC3339
            url: https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
        example: '2020-12-31T15:10:55Z'
      - name: to
        description: Point in time to end lookup (optional).
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
          description: The timestamp value formatted per RFC3339. This does allow nulls.
          example: '2020-12-31T15:10:55Z'
          externalDocs:
            description: RFC3339
            url: https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
        example: '2020-12-31T17:10:55Z'
      - in: query
        name: limit
        description: The maximum number of records that will be returned in a result set.
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 200
          default: 10
        example: 50
      - in: query
        name: offset
        description: The number of records to skip before starting to collect the result set. Used in conjunction with limit query parameter for pagination support
        required: false
        schema:
          type: integer
          minimum: 0
          default: 0
        example: 20
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: object
                required:
                - events
                - pagination
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      description: Event Dispatch object.
                      properties:
                        eventID:
                          type: string
                          format: uuid
                          description: A universally unique identifier (Version 4) as defined in RFC4122. This does not allow nulls.
                          example: dc0dc633-1760-4d43-ba1d-da94ed701f06
                          externalDocs:
                            description: RFC4122
                            url: https://datatracker.ietf.org/doc/html/rfc4122.html
                        eventTime:
                          type: string
                          format: date-time
                          description: The timestamp value formatted per RFC3339. This does not allow nulls.
                          example: '2020-12-31T15:10:55Z'
                          externalDocs:
                            description: RFC3339
                            url: https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
                        dispatchExecutionTime:
                          type: string
                          format: date-time
                          description: The timestamp value formatted per RFC3339. This does not allow nulls.
                          example: '2020-12-31T15:10:55Z'
                          externalDocs:
                            description: RFC3339
                            url: https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
                        eventType:
                          type: string
                        status:
                          type: string
                          enum:
                          - SUCCESS
                          - FAILURE
                          - PENDING
                      required:
                      - eventID
                      - eventTime
                      - dispatchExecutionTime
                      - eventType
                      - status
                      example:
                        eventID: 581a07f8-76fd-4394-903d-ba3dfd1de460
                        eventTime: '2020-12-31T15:10:55Z'
                        dispatchExecutionTime: '2020-12-31T15:10:55Z'
                        eventType: breadpayments.webhooks.my.super-rev1
                        status: SUCCESS
                  pagination:
                    type: object
                    description: pagination for response
                    required:
                    - limit
                    - offset
                    - total
                    properties:
                      limit:
                        type: integer
                        description: number or records to return
                        example: 10
                      offset:
                        type: integer
                        description: first record to return
                        example: 10
                      total:
                        type: integer
                        description: total records to be queried
                        example: 1500
        '400':
          description: Default error response for any errors in the API
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
        '401':
          description: Unauthorized. Indicates that provided credentials is not valid
          content:
            text/plain:
              schema:
                type: string
                example: Jwt is expired
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 401
                domain: Auth
                message: Invalid authentication
                reason: Invalid_Authentication
        '403':
          description: Forbidden. Indicates that request cannot be authorized
          content:
            text/plain:
              schema:
                type: string
                example: 'RBAC: Access Denied'
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 403
                domain: Auth
                message: 'RBAC: Access Denied'
                reason: Access_Denied
        '404':
          description: Not Found. Resource could not be found
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 404
                domain: Webhook
                message: Not Found. Subscription could not be found
                reason: Not_Found
        '500':
          description: Default error response for any errors in the API
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
  /api/webhook/subscription/{name}/event/{id}/dispatch:
    post:
      tags:
      - Events
      summary: Replay an event
      description: Allows a user to replay an event by supplying the event id. Upon success, the event will be replayed and a 200 response will be returned along with the dispatch status of that event.
      operationId: replayEventBySubscriptionNameAndEventID
      security:
      - bearerAuthWebhook:
        - r:webhook.event
      parameters:
      - name: name
        description: Name of the subscription
        in: path
        required: true
        schema:
          type: string
        example: Test1SubscriptionEndpoint-dbef2daf-f94a-41f3-8d07-52eb17cc17b3
      - name: id
        description: ID of the event
        in: path
        required: true
        schema:
          type: string
          format: uuid
          description: A universally unique identifier (Version 4) as defined in RFC4122. This does not allow nulls.
          example: dc0dc633-1760-4d43-ba1d-da94ed701f06
          externalDocs:
            description: RFC4122
            url: https://datatracker.ietf.org/doc/html/rfc4122.html
        example: c4ab7caa-2240-42f3-a300-5cb2b61456f5
      responses:
        '200':
          description: Status of dispatch record.
          content:
            application/json:
              schema:
                type: object
                description: Event Dispatch object.
                properties:
                  eventID:
                    type: string
                    format: uuid
                    description: A universally unique identifier (Version 4) as defined in RFC4122. This does not allow nulls.
                    example: dc0dc633-1760-4d43-ba1d-da94ed701f06
                    externalDocs:
                      description: RFC4122
                      url: https://datatracker.ietf.org/doc/html/rfc4122.html
                  eventTime:
                    type: string
                    format: date-time
                    description: The timestamp value formatted per RFC3339. This does not allow nulls.
                    example: '2020-12-31T15:10:55Z'
                    externalDocs:
                      description: RFC3339
                      url: https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
                  dispatchExecutionTime:
                    type: string
                    format: date-time
                    description: The timestamp value formatted per RFC3339. This does not allow nulls.
                    example: '2020-12-31T15:10:55Z'
                    externalDocs:
                      description: RFC3339
                      url: https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
                  eventType:
                    type: string
                  status:
                    type: string
                    enum:
                    - SUCCESS
                    - FAILURE
                    - PENDING
                required:
                - eventID
                - eventTime
                - dispatchExecutionTime
                - eventType
                - status
                example:
                  eventID: 581a07f8-76fd-4394-903d-ba3dfd1de460
                  eventTime: '2020-12-31T15:10:55Z'
                  dispatchExecutionTime: '2020-12-31T15:10:55Z'
                  eventType: breadpayments.webhooks.my.super-rev1
                  status: SUCCESS
        '400':
          description: Default error response for any errors in the API
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
        '401':
          description: Unauthorized. Indicates that provided credentials is not valid
          content:
            text/plain:
              schema:
                type: string
                example: Jwt is expired
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 401
                domain: Auth
                message: Invalid authentication
                reason: Invalid_Authentication
        '403':
          description: Forbidden. Indicates that request cannot be authorized
          content:
            text/plain:
              schema:
                type: string
                example: 'RBAC: Access Denied'
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 403
                domain: Auth
                message: 'RBAC: Access Denied'
                reason: Access_Denied
        '404':
          description: Not Found. Resource could not be found
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 404
                domain: Webhook
                message: Not Found. Subscription could not be found
                reason: Not_Found
        '500':
          description: Default error response for any errors in the API
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
components:
  securitySchemes:
    bearerAuthWebhook:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: The JWT access token provided by the Auth service.
