openapi: 3.2.0
info:
  title: Servicing As Low As API
  description: Servicing supports a buyer's post purchase journey, enabling viewing and management of payment agreements across all payment products.
  version: 2.0.0
  contact:
    email: partnership-growth@getbread.com
servers:
- url: https://api-preview.platform.breadpayments.com/
  description: Preview environment
- url: https://api.platform.breadpayments.com/
  description: Production environment
tags:
- name: As Low As
paths:
  /api/experience/servicing/as-low-as:
    get:
      operationId: getAsLowAs
      tags:
      - As Low As
      summary: Get As-Low-As
      description: Retrieve the as low as monthly pricing for a given product
      security: []
      parameters:
      - name: merchantId
        in: query
        description: ID of the merchant associated with the program.
        required: true
        schema:
          type: string
          format: uuid
        example: dc0dc633-1760-4d43-ba1d-da94ed701f06
      - name: amount
        in: query
        description: The total price in cents of the item or cart that you wish to calculate a monthly as low as amount for.
        required: true
        schema:
          type: integer
          format: int
        example: 50000
      - name: programId
        in: query
        description: Financing program used to perform as low as calculations.
        required: false
        schema:
          type: string
          format: uuid
        example: dc0dc633-1760-4d43-ba1d-da94ed701f06
      responses:
        '200':
          description: The as low as offering.
          content:
            application/json:
              schema:
                description: Information on the as low as offering.
                type: object
                properties:
                  asLowAs:
                    type: object
                    required:
                    - terms
                    - paymentAmount
                    - minRate
                    - maxRate
                    - promptText
                    - paymentAmountText
                    properties:
                      terms:
                        allOf:
                        - type: object
                          required:
                          - amount
                          - interval
                          - length
                          - rate
                          properties:
                            amount:
                              allOf:
                              - required:
                                - currency
                                - value
                                properties:
                                  currency:
                                    type: string
                                    description: The three letter currency code as defined in ISO 4217.
                                    example: USD
                                    minLength: 3
                                    maxLength: 3
                                    externalDocs:
                                      description: ISO 4217
                                      url: https://en.wikipedia.org/wiki/ISO_4217
                                  value:
                                    type: integer
                                    description: 'Monetary value as an integral number of the currency fractional unit e.g for USD: cents'
                                    format: int64
                                    example: 100
                                description: Represents a monetary amount in the specified currency
                                example:
                                  currency: USD
                                  value: 50000
                              description: The total amount for the term
                            interval:
                              allOf:
                              - type: string
                                description: Defines set of valid term intervals for a payment product
                                enum:
                                - BIWEEKLY
                                - MONTHLY
                              description: The payment interval for the term
                            length:
                              type: integer
                              format: int64
                              description: Length of the term
                              example: 12
                            rate:
                              type: number
                              format: float
                              description: The interest rate for the term
                              example: 5.75
                          description: Represents the terms offered for a payment product
                        description: The terms used to determine the payment
                      paymentAmount:
                        allOf:
                        - required:
                          - currency
                          - value
                          properties:
                            currency:
                              type: string
                              description: The three letter currency code as defined in ISO 4217.
                              example: USD
                              minLength: 3
                              maxLength: 3
                              externalDocs:
                                description: ISO 4217
                                url: https://en.wikipedia.org/wiki/ISO_4217
                            value:
                              type: integer
                              description: 'Monetary value as an integral number of the currency fractional unit e.g for USD: cents'
                              format: int64
                              example: 100
                          description: Represents a monetary amount in the specified currency
                          example:
                            currency: USD
                            value: 50000
                        description: The cost of each payment based on the terms
                      minRate:
                        type: number
                        format: float
                        description: The minimum interest rate that may be offered
                        example: 2.99
                      maxRate:
                        type: number
                        format: float
                        description: The maximum interest rate that may be offered
                        example: 29.99
                      promptText:
                        type: object
                        additionalProperties:
                          type: string
                        description: The financing disclosure text that can be provided to the buyer in the appropriate language
                        example:
                          en-us: A sample prompt text in the appropriate locale
                          ca-fr: Un exemple de texte en français canadien
                      paymentAmountText:
                        type: object
                        additionalProperties:
                          type: string
                        description: The payment amount with the appropriate formatting
                        example:
                          en-us: $150.25
                          ca-fr: 150.25 $
                    description: Represents a sample offer with the appropriate user prompts for a given amount and apr along with apr bounds
                  programId:
                    description: Financing program used to perform as low as calculations.
                    type: string
                    format: uuid
                    example: a5773535-602e-4b1f-aad7-f4d163a38b3f
        '400':
          description: Response for Bad Request Errors by as_low_as service.
          content:
            application/json:
              schema:
                description: Represents a error returned by as_low_as service.
                type: object
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                properties:
                  reason:
                    type: string
                    description: As Low As error reason codes
                    enum:
                    - Bad_Request
                    example: Bad_Request
                example:
                  message: Bad Request
                  reason: Bad_Request
                  domain: ''
                  metadata: {}
                  code: 400
        '500':
          description: Response for Internal Server Errors returned by as_low_as service.
          content:
            application/json:
              schema:
                description: As-low-as.
                type: object
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                properties:
                  reason:
                    type: string
                    description: As Low As error reason codes
                    enum:
                    - Internal_Server_Error
                    - Dependency_Unavailable
                    example: Internal_Server_Error
                example:
                  message: Internal Server Error
                  reason: Internal_Server_Error
                  domain: ''
                  metadata: {}
                  code: 500
  /api/experience/dynamic-financing/loan-terms:
    get:
      operationId: getFinancingLoanTerms
      tags:
      - As Low As
      summary: Get financing/loan-terms
      description: Retrieve loan terms copy for financing page
      parameters:
      - name: merchantId
        in: query
        description: ID of the merchant associated with the program.
        required: true
        schema:
          type: string
          format: uuid
        example: dc0dc633-1760-4d43-ba1d-da94ed701f06
      - name: programId
        in: query
        description: Financing program used to perform as low as calculations.
        required: false
        schema:
          type: string
          format: uuid
        example: dc0dc633-1760-4d43-ba1d-da94ed701f06
      responses:
        '200':
          description: Payment plan copy.
          content:
            application/json:
              schema:
                description: Loan terms subhead and SubheadInstallmentdisclosuresymbol on financing page.
                type: object
                properties:
                  subhead:
                    description: Loan terms subhead text
                    type: string
                    format: string
                    example: Pay for your order over 3, 6 12, 24, 36 months at competitive rates*.
                  subheadInstallmentdisclosuresymbol:
                    description: Disclosure symbol for Installment subhead
                    type: string
                    format: string
                    example: '*'
        '400':
          description: Response for Bad Request Errors by as_low_as service.
          content:
            application/json:
              schema:
                description: Represents a error returned by as_low_as service.
                type: object
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                properties:
                  reason:
                    type: string
                    description: As Low As error reason codes
                    enum:
                    - Bad_Request
                    example: Bad_Request
                example:
                  message: Bad Request
                  reason: Bad_Request
                  domain: ''
                  metadata: {}
                  code: 400
        '500':
          description: Response for Internal Server Errors returned by as_low_as service.
          content:
            application/json:
              schema:
                description: As-low-as.
                type: object
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                properties:
                  reason:
                    type: string
                    description: As Low As error reason codes
                    enum:
                    - Internal_Server_Error
                    - Dependency_Unavailable
                    example: Internal_Server_Error
                example:
                  message: Internal Server Error
                  reason: Internal_Server_Error
                  domain: ''
                  metadata: {}
                  code: 500
components:
  securitySchemes:
    bearerAuthServicing:
      type: http
      scheme: bearer
      bearerFormat: JWT
    bearerAuthDisclosure:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token provided by the Auth service
