openapi: 3.2.0
info:
  title: webhook Client Management API
  description: Provides support for managing webhook subscriber's events by allowing them to query, and ultimately replay past failed events.
  version: 2.0.0
  contact:
    email: Core-Eng@breadfinancial.com
servers:
- url: https://api-preview.platform.breadpayments.com/
  description: Preview environment
- url: https://api.platform.breadpayments.com/
  description: Production environment
tags:
- name: Client Management
paths:
  /api/webhook/client/jwks:
    get:
      security:
      - bearerAuthWebhook:
        - r:webhook.subscription
      tags:
      - Client Management
      summary: List JWKs
      description: Retrieve list of JWK that are used for signing outgoing subscription requests
      operationId: getClientJWKs
      responses:
        '200':
          description: List of JWKs belonging to client
          content:
            application/json:
              schema:
                type: object
                description: Object containing list of JWK
                properties:
                  keys:
                    type: array
                    items:
                      type: object
                      properties:
                        k:
                          type: string
                          description: base64 URL encoded key
                        kty:
                          type: string
                          description: key type
                        kid:
                          type: string
                          description: key id
                        use:
                          type: string
                          description: intended use
                        alg:
                          type: string
                          description: algorithm used to encode signature
                      required:
                      - k
                      - kty
                      - kid
                      - use
                      - alg
                required:
                - keys
        '304':
          description: Response when client should use cached results
          headers:
            Cache-Control:
              description: defines TTL of resource in seconds, indicates that the response can be stored in caches, and indicates that the response can be stored only in a private cache
              example: 'max-age: 86400, must-revalidate, private'
              schema:
                type: string
            ETag:
              description: indicate the current version of the resource
              example: c4ab7caa-2240-42f3-a300-5cb2b61456f5
              schema:
                type: string
        '401':
          description: Unauthorized. Indicates that provided credentials is not valid
          content:
            text/plain:
              schema:
                type: string
                example: Jwt is expired
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 401
                domain: Auth
                message: Invalid authentication
                reason: Invalid_Authentication
        '403':
          description: Forbidden. Indicates that request cannot be authorized
          content:
            text/plain:
              schema:
                type: string
                example: 'RBAC: Access Denied'
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 403
                domain: Auth
                message: 'RBAC: Access Denied'
                reason: Access_Denied
        '404':
          description: Not Found. Resource could not be found
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
              example:
                code: 404
                domain: Webhook
                message: Not Found. Subscription could not be found
                reason: Not_Found
        '500':
          description: Default error response for any errors in the API
          content:
            application/json:
              schema:
                allOf:
                - required:
                  - code
                  - domain
                  - message
                  type: object
                  properties:
                    code:
                      type: integer
                      description: The underlying http status code
                      format: int32
                      example: 500
                    message:
                      type: string
                      description: A simple message in english describing the error and can be returned to the consumer
                      example: Age cannot be less than 18
                    domain:
                      type: string
                      description: The domain where the error is originating from as defined by the service
                      example: Payments
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                      description: Any additional details to be conveyed as determined by the service. If present, will return map of key value pairs
                      example:
                        propertyName: propertyName is required
                required:
                - code
                - domain
                - message
                - reason
                type: object
                properties:
                  reason:
                    type: string
                    description: A reason code specific to the service and can be used to identify the exact issue. Should be unique within a domain
                    example: Reason_Code
components:
  securitySchemes:
    bearerAuthWebhook:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: The JWT access token provided by the Auth service.
